### ISSUE TITLE
报错求助

### ISSUE THREAD

**Issue by hygine** [cauyrd/EgoNet#1]
searching sub-network...
Traceback (most recent call last):
  File "egonet.py", line 287, in <module>
    myclf.rank_gene(data_dict, score, gene_rank_output)
  File "egonet.py", line 198, in rank_gene
    forest = RandomForestClassifier(compute_importances=True, random_state=0, n_jobs=-1)
TypeError: __init__() got an unexpected keyword argument 'compute_importances'

**Comment by cauyrd** [comment]
This is because you are using a very new version of scikit-learn which has rewrite the RandomFroestClassifier function. To run EgoNet, you have to use sklearn 0.14 version at https://github.com/scikit-learn/scikit-learn/releases/tag/0.14

**Comment by hygine** [comment]
thank you.
